export const FETCH_ALL_BREEDS = 'FETCH_ALL_BREEDS';
export const FETCH_SINGLE_BREED = 'FETCH_SINGLE_BREED';
export const SET_DISPLAYED_BREEDS = 'SET_DISPLAYED_BREEDS';
export const CHANGE_MY_BREEDS = 'CHANGE_MY_BREEDS';
export const SET_BREEDS_FILTER = 'SET_BREEDS_FILTER';
export const ENTER_SEARCH = 'ENTER_SEARCH';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const SET_IMAGES = 'SET_IMAGES';
